title: 日志
description: My Personal Stack Problems
author: zofia
github: https://github.com/ZofiaMiao
about: 好好学习，天天向上
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-weibo
      link: "http://weibo.com/ahongmei?refer_flag=1001030101_"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-github
      link: "https://github.com/ZofiaMiao"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
